### ISSUE TITLE
TrombLoader keeps calling me a liar

### ISSUE THREAD

**Issue by Steev-Steev** [JohnGrubba/TromboneChampAutomod#1]
I do as the loader tells me however the Trombone Champ on Steam does not seem to be recognized by the loader. Starting it and exiting then hitting the enter never triggers anything except the try again feedback.

![image](https://user-images.githubusercontent.com/116850641/198414506-b209cdb0-99f5-4abb-9504-fd766885d176.png)

**Comment by JohnGrubba** [comment]
The Screenshot tells me something different but can you give me a Screenshot of the folder structure in your Trombone Champ Installation folder?
![image](https://user-images.githubusercontent.com/63007476/198535527-64ca5b2c-680f-4515-8afa-bd3f364a5828.png)
![image](https://user-images.githubusercontent.com/63007476/198535738-2ac9fe41-c925-4d42-9820-0229453a5342.png)

**Comment by JohnGrubba** [comment]
Download the New Release and just do what the Terminal tells you. And if it says that you are a liar, send screenshot of the terminal and the Directorys i listed above this Comment. And make sure you have trombone champ closed before you hit enter.

**Comment by JohnGrubba** [comment]
Fixed in V1.2
