### ISSUE TITLE
Directory Defaults to C

### ISSUE THREAD

**Issue by notbutnot** [JohnGrubba/TromboneChampAutomod#2]
When using Loader for the first time, Loader.exe assumes the game is installed on the C drive. I have multiple drives, and Trombone Champ is currently installed on E. Loader can't find the actual directory and there's currently no way to tell the program where the installation drive is.

**Comment by JohnGrubba** [comment]
This will be fixed right now! It normally reads the Steam Installation directory from the Registry but seems like you somehow got around this🤣 I will implement this now! Thanks for the Feedback!

**Comment by JohnGrubba** [comment]
Fixed in V1.2
