### ISSUE TITLE
This is Halloween song missing from list

### ISSUE THREAD

**Issue by Elarith** [JohnGrubba/TromboneChampAutomod#3]
At least one song is missing. The only one I found was This is Halloween

**Comment by JohnGrubba** [comment]
Updating the Songs from the Excel to here is done by TheGlitched64. He will add those soon ( i hope so )

**Comment by TheGlitched64** [comment]
As of now whats in the file is every chart made before the 29th of October. Adding more now from 29/10 to 4/11 and beyond slowly but surely. If there are any missing from BEFORE this date though please let me know.
